version: 2

sources:
  - name: investimentos #qualquer nome pode ser escolhido
    schema: public
    description: dados que vieram do backend
    tables:
      - name: fatura_jornada
      - name: fatura_jornada_small
      - name: fatura_redrex
      - name: fatura_redrex_small